/* =========================================================
   Squer TCG - Abilità di gioco (Squer Clash)
   6 effetti, uno per carta, risolti nello scontro di zona.
   Assegnazione per nome carta (da carte.md): modificabile qui.
   Carte non presenti in mappa -> effetto stabile dal seed.
   ========================================================= */

var SQUER = window.SQUER || (window.SQUER = {});

// ---- i 6 effetti ----
// text = descrizione breve mostrata sulla carta (testo normale, dopo il nome)
const ABILITIES = {
  fortuna:    { id: 'fortuna',    symbol: '🍀', name: 'Fortuna',    text: 'Se vinci lo scontro, segni +30 PV.' },
  rivincita:  { id: 'rivincita',  symbol: '💥', name: 'Rivincita',  text: 'Se perdi, segni comunque metà dei tuoi PV.' },
  scudo:      { id: 'scudo',      symbol: '🛡️', name: 'Scudo',      text: "Se perdi, l'avversario segna metà dei tuoi PV." },
  specchio:   { id: 'specchio',   symbol: '🪞', name: 'Specchio',   text: 'A PV uguali o tipo neutro, vinci tu.' },
  sbruffone:  { id: 'sbruffone',  symbol: '😎', name: 'Sbruffone',  text: "Con più PV dell'avversaria, segni +50%." },
  imprevisto: { id: 'imprevisto', symbol: '🎲', name: 'Imprevisto', text: 'In vantaggio di tipo, segni +50%.' },
};

// ---- assegnazione per nome carta (da carte.md) ----
const ABILITY_BY_NAME = {
  // comuni (70)
  "Basic Squer": "fortuna",
  "Default Squer": "scudo",
  "Happy Squer": "fortuna",
  "Egypt Squer": "fortuna",
  "Squer Merende": "rivincita",
  "Grin Squer": "specchio",
  "Flashy Squer": "fortuna",
  "Squer Regrets": "scudo",
  "Bombing Squer": "imprevisto",
  "Staring Squer": "specchio",
  "Wild Squer": "rivincita",
  "Lost Squer": "scudo",
  "Landscape Squer": "fortuna",
  "Challenging Squer": "specchio",
  "Coffee Squer": "fortuna",
  "Squer Milano A": "fortuna",
  "Squer Milano B": "rivincita",
  "Squer Toxicity Evening 2": "rivincita",
  "Chad Squer": "sbruffone",
  "Suspicious Squer": "specchio",
  "Confident Squer": "sbruffone",
  "Potato Squer": "scudo",
  "Spaghetti Squer": "fortuna",
  "Sisterhood Squer": "scudo",
  "Very Interested Squer": "fortuna",
  "Squer Toxicity Evening": "rivincita",
  "Yellow Squer": "fortuna",
  "Meh Squer": "scudo",
  "Doggy Squer": "fortuna",
  "Stunned Squer": "scudo",
  "Great Idea Squer": "imprevisto",
  "Helping Squer": "scudo",
  "Pleased Squer": "fortuna",
  "Not Impressed Squer": "specchio",
  "Great Time Squer": "fortuna",
  "Evading Squer": "scudo",
  "Oops Squer": "rivincita",
  "Country Squer": "fortuna",
  "Cosplay Party Squer": "fortuna",
  "Cute Squer": "scudo",
  "Pool Squer": "fortuna",
  "Cold Squer": "scudo",
  "Eye Contact Squer": "specchio",
  "Squer Fan A": "fortuna",
  "Squer Fan B": "scudo",
  "Squer Fan C": "rivincita",
  "Dont F Ck With Squer": "rivincita",
  "Brindisi Squer": "fortuna",
  "Squer e Vabbe": "specchio",
  "Groove Squer": "fortuna",
  "Squer Del Boschetto": "fortuna",
  "Jenga Squer": "rivincita",
  "Travel Squer": "fortuna",
  "Lightbulb Squer": "imprevisto",
  "Thinking Squer": "specchio",
  "Rainy Squer": "scudo",
  "Problem Solving Squer": "sbruffone",
  "Cocktail Squer": "fortuna",
  "Mocking Squer": "specchio",
  "Searching Squer": "fortuna",
  "Bored Squer": "scudo",
  "Squer Amigos": "scudo",
  "Squer Amigos Bar": "fortuna",
  "Squer Amigos Home": "scudo",
  "Squer Amigos Mirror": "specchio",
  "Squer Amigos Pizza": "fortuna",
  "Squer Amigos Sfocati": "specchio",
  "Squer Amigos Streets A": "fortuna",
  "Squer Amigos Streets B": "scudo",
  "Squer Amigos Young": "fortuna",

  // non comuni (50)
  "Accompanied Squer": "scudo",
  "Epiphany Squer": "imprevisto",
  "Wasted Squer": "rivincita",
  "Twin Squer": "specchio",
  "Italian Trash Squer": "rivincita",
  "Troublemaker Squer": "imprevisto",
  "Vampire Squer": "rivincita",
  "Squer Malandrino": "imprevisto",
  "Pizza Squer": "fortuna",
  "Squeyer": "specchio",
  "Wallpaper Squer": "scudo",
  "Squer Barney A": "specchio",
  "Squer Barney B": "fortuna",
  "Squer Barney C": "scudo",
  "Squer Barney D": "rivincita",
  "Station Squer": "scudo",
  "Half Dead Squer": "rivincita",
  "Photobomb Cosplay Squer": "imprevisto",
  "Beach Squer": "fortuna",
  "Squer Che Sa Qualcosa A": "specchio",
  "Squer Che Sa Qualcosa B": "imprevisto",
  "Choppy Squer": "rivincita",
  "Vision Squer": "imprevisto",
  "Wrong Frame Squer": "scudo",
  "Squer Of Thrones": "sbruffone",
  "Pride Squer": "sbruffone",
  "Rainbow Squer": "fortuna",
  "Party Hard Squer": "fortuna",
  "Wanted Squer": "rivincita",
  "Popping Squer": "imprevisto",
  "Lan Party Squer": "fortuna",
  "Spider Squer Origins": "scudo",
  "Background Squer": "scudo",
  "Elegant Squer": "sbruffone",
  "Abbiocco Squer": "scudo",
  "Squering": "specchio",
  "Screen Squer": "scudo",
  "Champagne Squer": "fortuna",
  "Squer Sfumato": "scudo",
  "Lockdown Party Squer": "rivincita",
  "Not Convinced Squer": "specchio",
  "Squer Cualcosa Collab": "fortuna",
  "Weird God Squer": "imprevisto",
  "Evil Squer": "imprevisto",
  "Blooming Squer": "fortuna",
  "Mystic Squer": "imprevisto",
  "Xmas Squer": "fortuna",
  "Canada Squer": "fortuna",
  "Mista Squer": "rivincita",
  "Not So Happy Squer": "scudo",

  // rare (35)
  "Driver Squer": "sbruffone",
  "Architect Squer": "scudo",
  "Squer Ranger": "specchio",
  "Parliament Squer": "sbruffone",
  "Post Pool Party Squer": "fortuna",
  "Canvas Squer": "specchio",
  "Bottle Opener Squer": "rivincita",
  "King Squer": "sbruffone",
  "Squer Claus": "fortuna",
  "Pink Fluo Squer": "imprevisto",
  "Matera Squer": "scudo",
  "Swinging Squer": "imprevisto",
  "Distracted Squer": "scudo",
  "Augment Squer": "sbruffone",
  "30 Squer": "rivincita",
  "Fake Happy Squer": "imprevisto",
  "Sun God Squer": "imprevisto",
  "Mafia Squer": "imprevisto",
  "WTF Squer": "specchio",
  "Pusher Squer": "sbruffone",
  "Hole Squer": "scudo",
  "Coast Squer": "fortuna",
  "Degustibus Squer": "specchio",
  "Biker Squer": "sbruffone",
  "Hot Squer": "imprevisto",
  "Spider Squer": "imprevisto",
  "New Year Squer": "fortuna",
  "Young Squer": "fortuna",
  "Geralt Squer": "sbruffone",
  "Interference Squer": "imprevisto",
  "Figure Squer": "specchio",
  "Smith Squer": "sbruffone",
  "God Blessed Squer": "imprevisto",
  "Time Traveler Squer": "imprevisto",
  "Super Fast Squer": "specchio",

  // super rare (20)
  "Big Boss Squer": "sbruffone",
  "Bikini Squer": "imprevisto",
  "Crazy Squer": "imprevisto",
  "Door Squer": "scudo",
  "Dusty Squer": "scudo",
  "Everyone Is Squer": "specchio",
  "Guilty Squer": "rivincita",
  "Nostalgic Squer": "fortuna",
  "Omega Squer": "sbruffone",
  "Peaky Blinder Squer": "imprevisto",
  "Pika Squer": "imprevisto",
  "Rebooting Squer": "rivincita",
  "Sad Keanu Squer": "scudo",
  "Serial Killer Squer": "imprevisto",
  "She/Her Squer": "sbruffone",
  "Corsivoe Squer": "specchio",
  "Squer Sparrow": "sbruffone",
  "Squer Wick": "sbruffone",
  "Tree Squer": "scudo",
  "WinXP Squer": "specchio",

  // leggendarie (5)
  "Fucking Squer": "imprevisto",
  "The Photobomb Begins": "imprevisto",
  "La Congrega Reloaded": "sbruffone",
  "Surprise Frog Squer": "imprevisto",
  "Photobombing Squer": "imprevisto",
};

/** Effetto di una carta: dalla mappa per nome, altrimenti stabile dal seed.
    NON tocca il rng principale della carta (usa un seed dedicato), così
    l'aspetto visivo delle carte esistenti non cambia. */
function abilityForCard(card) {
  const byName = ABILITY_BY_NAME[card.name];
  if (byName && ABILITIES[byName]) return ABILITIES[byName];
  const rng = makeRNG(card.file + '::ability');
  const ids = Object.keys(ABILITIES);
  return ABILITIES[rng.pick(ids)];
}
